### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by yyan162** [yanosh-k/bulgarian_dictionary#1]
Hi Yanosh,

Thank you for putting the effort in creating the dictionary in which is something I am interested.

I do not read Bulgarian, but I nevertheless tested the dictionary after downloading a Bulgarian e-book, it seems that the dictionary cannot:

1. recognise words in capitals, or starts in capital letters;
2. recognise some forms in declensions and conjugations (especially conjugation).

Many thanks for your hard work.

Kind regards,
Yyan162

**Comment by yanosh-k** [comment]
After a long time I have finally managed to find time and fix those points (actually mainly point 1).

1. I've tried many things while trying for fix this, but what seems to work is I've added a UTF8 BOM character to the beginning of the `.opf` and `.html` files and reformatted the templates that generate them.
2. This is more of a limitation of the input database it does not contain all conjugation imaginable, but it tries its best. I've update the way conjugation are added in the dictionary, so this might resolve some of the problems.

**Comment by yanosh-k** [comment]
Turns out neither of the above fixes the issue. After further testing, it turns out, that I have to set the language of the dictionary to Russian in order to make the Kindle recognize capitalized versions of the worlds.

So the dictionary will now advertise itself as Russian. This is more of a dirty fix than an actual solution. The `.opf` file now reads as follows:
```
<?xml version="1.0"?><!DOCTYPE package SYSTEM "oeb1.ent">
<package unique-identifier="uid" xmlns:dc="Dublin Core">
    <metadata>
        <dc-metadata>
            <dc:Identifier id="uid">bulgarian_dictionary</dc:Identifier>
            <dc:Title><h2>Bulgarian Dictionary</h2></dc:Title>
            <dc:Creator>Yanosh Kunsh</dc:Creator>
            <dc:Language>ru</dc:Language>
        </dc-metadata>
        <x-metadata>
            <DictionaryInLanguage>ru</DictionaryInLanguage>
            <DictionaryOutLanguage>ru</DictionaryOutLanguage>
        </x-metadata>
    </metadata>
...
```

I'm closing the issue for now, but will keep an eye on for a possible solution.
